scrape_configs:
  - job_name: 'spring-boot-app'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8080']
        labels:
          application: "Advanced insert"